language: go
go: 1.11.x

install:
  - go get -u github.com/FiloSottile/gvt
  - make deps
script:
  - make build
  - make crossbuild
  - make docker-build

deploy:
  provider: script
  script: bin/docker-push
  # we don't need this for docker, but the artifacts push does
  skip_cleanup: true
  on:
    # push all non-PR builds to Docker Hub
    all_branches: true
    condition: "$TRAVIS_PULL_REQUEST == false"

addons:
  artifacts:
    paths:
    - ./build/linux/amd64/vsphere-monitor
    - ./build/darwin/amd64/vsphere-monitor
    target_paths:
    - travis-ci/vsphere-monitor/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    - travis-ci/vsphere-monitor/$(git describe --always --dirty --tags)
    - travis-ci/vsphere-monitor/$TRAVIS_BRANCH
